java_library(
    name = "resources",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/example:__pkg__",
    ],
    deps = [
        "//src/example/dtos",
        "//third_party:dropwizard_metrics_annotation",
        "//third_party:jakarta_ws",
    ],
)
